version: "2"
services:
  ldap:
    image: edtasixm06/ldap20:latest
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - "ldap-data:/var/lib/ldap"
      - "ldap-config:/etc/openldap/slapd.d"        
    networks:
     - 2hisix
  php:
    image: edtasixm06/phpldapadmin:20
    container_name: phpldapadmin.edt.org
    hostname: phpldapadmin.edt.org
    ports:
     - "80:80"
    networks:
     - 2hisix
  portainer:
    image: portainer/portainer
    container_name: portainer.edt.org
    hostname: portainer.edt.org
    ports: 
     - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock 
networks:
  2hisix:
volumes:
  ldap-data:
  ldap-config:

